{
  imports = [
    ./alacritty.nix
    ./gaming.nix
    ./git.nix
    ./gwenview.nix
    ./lutris.nix
    ./mangohud.nix
    ./pcmanfm-qt.nix
    ./pcmanfm.nix
    ./r2modman.nix
    ./spicetify.nix
    ./steam.nix
    ./thunar.nix
    ./vscodium.nix
    ./waybar
    ./wine.nix
    ./zsh.nix
  ];
}
